-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 22, 2023 at 06:16 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `flex_performance`
--

-- --------------------------------------------------------

--
-- Table structure for table `disciplinaries`
--

CREATE TABLE `disciplinaries` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `employeeID` bigint(20) UNSIGNED NOT NULL,
  `department` bigint(20) UNSIGNED NOT NULL,
  `suspension` text DEFAULT NULL,
  `date_of_charge` date DEFAULT NULL,
  `detail_of_charge` mediumtext DEFAULT NULL,
  `date_of_hearing` date DEFAULT NULL,
  `detail_of_hearing` mediumtext DEFAULT NULL,
  `findings` mediumtext DEFAULT NULL,
  `recommended_sanctum` mediumtext DEFAULT NULL,
  `final_decission` mediumtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `disciplinaries`
--

INSERT INTO `disciplinaries` (`id`, `employeeID`, `department`, `suspension`, `date_of_charge`, `detail_of_charge`, `date_of_hearing`, `detail_of_hearing`, `findings`, `recommended_sanctum`, `final_decission`, `created_at`, `updated_at`) VALUES
(9, 13596, 1, 'Suspended from doing Telling duties', '2019-03-20', '<p>The employee was charged with the following offences;<br>(i) Acts of theft, misappropriation and willful dishonesty against the employer under Rule 10.2.9 of BancABC Employment Code of Conduct ;<br>(ii) Fraudulent acts against the employer, under Rule 10.2.10 of BancABC Employment Code of Conduct;<br>(i) Serious misconduct resulting from willful dishonesty against the employer, under Rule 10.2.9 of BancABC Employment Code of Conduct;<br>(ii) Other Serious breach of Organizational rules or policy which have the effect of causing an irreparable breakdown in the employment relationship, under Rule 10.2.13;<br>(iii) Dishonesty and any other breach of trust under Rule 10.2.5 of the BancABC Employment Code of Conduct; <br></p>', '2019-04-03', '<p>a) Serious misconduct resulting from willful dishonesty against the employer, <br>b) Serious breach of Organizational rules or policy which have the effect of causing an irreparable breakdown in the employment relationship, and<br>c) Dishonesty and breach of trust.<br><br><br></p>', NULL, 'Final written warning letter', '<p>Final Written Warning Letter<br></p>', '2023-02-07 04:46:09', '2023-02-07 04:46:09'),
(10, 101786, 2, 'N/A', NULL, '<p>The employee was charged with the following offences :<br><br>(i) Fof work, under Rule 10.2.3 of BancABC Employment Code of Conduct;<br>(ii) Acts of willful dishonestly against the employer, under Rule 10.2.9 of BancABC Employment Code of Conduct;<br>(iii) Serious breach of Organizational rules and Policy which have the effect of causing an irreparable breakdown in the employment relationship, under Rule 10.2.13; and<br>(iv) Dishonesty and breach of trust under Rule 10.2.5 of the BancABC Employment Code of Conduct; <br></p>', '2019-05-07', '<p>a) The accused used to be among the Graduate Trainees attached at Treasury department and the record indicates that 2018 was her first year then she was solely in charge as a Trading dealer.&nbsp;&nbsp; &nbsp;<br>b) Circumstances/ grounds that lead to this misconduct – it was also noted when this incident occurs, she was double hutting two roles (money market and FX trading) this was due to shortage of staff at the dealing room and liquidity pressure experienced at that particular time.&nbsp; &nbsp;<br>c) Regulatory consequences, business impact and of the bank’s reputational damage resulting from noncompliance with IFEM Treasury Code of Conduct.<br></p>', NULL, 'Final written warning letter', '<p>Final written warning letter<br></p>', '2023-02-07 04:50:42', '2023-02-07 04:50:42'),
(12, 100199, 3, 'N/A', '2019-07-09', 'The employee was charged with the following offences :<br><br>(i)&nbsp;&nbsp; &nbsp;General misconduct of breaching organizational rules by not coming to work without advice or providing justifiable or reasonable cause; under Rule 10.1.11 of BancABC Employment Code of Conduct.', '2019-07-24', 'a) He has not reported to work for six (6) days from 24th June 2019 to 1st July 2019 without notifying or seeking permission from his Supervisor/Line Manager<br>b) He has breached BancABC Employee code of conduct by been absent from work for over five (5) days without permission. <br>c) He has not performed his duties as employee by not showing up to work for 6 working day<br><br>', NULL, 'Written warning letter and should be monitored for six months', '<p>Written Warning Letter<br></p>', '2023-02-07 05:01:12', '2023-02-07 05:01:12'),
(13, 100450, 7, 'N/A', '2019-09-24', '<p>The employee was charged with the following offences :<br><br>(i)&nbsp;&nbsp;&nbsp; General misconduct of breaching organizational rules by not coming to work without advice or providing justifiable or reasonable cause; under Rule 10.1.11 of BancABC Employment Code of Conduct.<br></p>', '2019-10-22', '<p>a)The Complainant was not fully versed with all particulars of the case and could not fully elaborate on the allegation statements.<br>b) Failure to implement the procurement process when appointing vendors to serve the bank.<br>c) Absence of indications that Elikana caused a substantial loss of TZS. 40 Million to the bank.<br>d) Elikana did not receive instruction to conduct a physical search of the vendors ‘local showroom.<br></p>', '<p><br></p>', 'None', '<p>Case was Dismissed<br></p>', '2023-02-07 05:03:42', '2023-02-07 05:03:42'),
(16, 13659, 8, 'N/A', '2019-03-20', '<p>The employee was charged with the following offences :</p><p><br></p><p>(i) Falsification of records, under Rule 10.2.18 of BancABC Employment Code of Conduct;</p><p>(ii) Habitual, substantial, or willful negligence in performance of work under Rule 10.2.3 of BancABC Employment Code of Conduct;</p><p>(iii) Serious misconduct resulting from willful dishonesty against the employer, under Rule 10.2.9 of BancABC Employment Code of Conduct;</p><p>(iv) Dishonesty or any other breach of trust, under Rule 10.2.5 of BancABC Employment Code of Conduct;</p><p>(v) Other Serious breach of Organizational rules or policy which have the effect of causing an irreparable breakdown in the employment relationship, under Rule 10.2.13;</p>', '2019-10-12', '<p>a) Lack of Prior Approval</p><p>b) Habitual, substantial, or willful negligence in performance of work</p><p>c) Lack of Integrity</p><p>d) He stand to see he is right while he is wrong</p><p><br></p>', NULL, 'Final written warning letter', '<p>Final written warning letter<br></p>', '2023-02-21 06:25:18', '2023-02-21 06:25:18'),
(17, 13603, 4, 'N/A', '2019-07-09', '<p>The employee was charged with the following offences :</p><p><br></p><p>(i)<span style=\"white-space:pre\">	</span>Poor timekeeping i.e. persistently reporting to work or leaving work early without authorization or just o reasonable cause; or taking extended or unauthorized breaks during working hours, under Rule 10.1.1 of BancABC Employment Code of Conduct;</p><p>(i)<span style=\"white-space:pre\">	</span>General misconduct of breaching organizational rules by not coming to work without advice or providing justifiable or reasonable cause; under Rule 10.1.11 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)<span style=\"white-space:pre\">	</span>Misconduct of malingering by failing without reasonable cause to expeditiously complete set assignments; under Rule 10.1.10 of BancABC Employment Code of Conduct;</p><p>(iii)<span style=\"white-space:pre\">	</span>Serious Misconduct of habitual negligence in the performance of your duties; under Rule 10.2.3 of BancABC Employment Code of Conduct; and</p><p>(iv)<span style=\"white-space:pre\">	</span>Serious Misconduct by conducting yourself in an unprofessional manner.</p>', '2019-07-24', '<p>a) Poor timekeeping. Reporting to work or leaving early without authorization from his Supervisor&nbsp;</p><p>b) He has not reported to work several days between May 2018 to July 2019 as per emails communications between his supervisors, HC and accused&nbsp;</p><p>c) He failed to provide medical report which can prove his medical case&nbsp;</p><p>d) Negligence in performing his duties by coming late at work, absenteeism , mismanagement of customers i.e. A1 outdoor&nbsp;&nbsp;</p>', NULL, 'Final written warning letter and should be in special supervision for six months, in case he repeats any of the above offence should be charged immediately.', '<p>Final Written Warning Letter<br></p>', '2023-02-21 06:48:41', '2023-02-21 06:48:41'),
(18, 13623, 4, 'Suspended from duty', '2020-07-13', '<p>The employee was charged with the following offences;</p><p>(i) Being absent from work without permission or reasonable cause for up to five (5) working days in your case its over five (5) weeks, under Rule 10.2.1 of BancABC Employment Code of Conduct and Human Capital Policy and Procedure Manuel Chapter 3.5.5, 3.5.6 and 3.5.7.</p><p>(ii) Insubordination, that is, disrespectful conduct towards the employer by deed, under Rule 10.2.2 of BancABC Employment Code of Conduct and Human Capital Policy and Procedure Manual Chapter 3 Section 3.4.8, 3.5.5, 3.5.6 and 3.5.7.</p>', '2020-08-05', '<p>a) For being absent from work for more than five (5) consecutive working days without authorization, justification or reasonable cause which is a Serious Misconduct under Rule 10.2.1 of the BancABC Employment Code of Conduct under the category of offences that constitutes termination;</p><p>b) For neglecting to observe the procedures set and deliberately proceeded to take unauthorized leave which is a serious breach of the banks Human Capital Policy and Procedure Manual Chapter 3.4.8, 3.5.5, 3.5.6 and 3.5.7;</p><p>c) For Insubordination, that is, disrespectful conduct towards the employer by deed which is a Serious Misconduct under Rule 10.2.2 of the BancABC Employment Code of Conduct.</p>', NULL, 'Termination of employment', '<p>Termination of employment</p>', '2023-02-21 07:06:13', '2023-02-21 07:12:23'),
(19, 13447, 4, 'Suspended from duty', '2021-06-09', '<p>The employee was charged with the following offences:</p><p>(i)Serious Breach of Organizational rules and Policy by violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5 and 25 of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”); and</p><p>(iii)Substantial negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct</p><div><br></div>', '2021-06-23', '<p>The Committee found the accused guilty of all charges brought against her.<br></p>', NULL, 'Termination of employment', '<p>Termination of Employment<br></p>', '2023-02-21 07:14:36', '2023-02-21 07:14:36'),
(20, 13607, 1, 'Suspended from duty', '2021-06-09', '<p>The employee was charged with the following offences :</p><p>(i)<span style=\"white-space:pre\">	</span>Serious Breach of Organizational rules and Policy by violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)<span style=\"white-space:pre\">	</span>Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5 and 25 of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”); and</p><p>(iii)<span style=\"white-space:pre\">	</span>Substantial negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct.</p>', '2021-06-23', '<p>The Committee found the accused guilty of all charges brought against him.<br></p>', NULL, 'Termination of employment', '<p>Termination of employment<br></p>', '2023-02-21 07:34:06', '2023-02-21 07:34:06'),
(21, 13596, 4, 'N/A', '2021-08-10', '<p>(i)Serious Misconduct under Rule 10.2.5 of BancABC Employment Code of Conduct resulting from Dishonestly or any other breach of trust;</p><p>(ii)Serious Misconduct under Rule 10.2.9 of BancABC Employment Code of Conduct resulting from willful dishonesty against the employer, another employee, or a customer or client of the employer;</p><p>(iii)Serious Misconduct under Rule 10.2.10 of BancABC Employment Code of Conduct resulting from Fraud or misappropriation of organizational funds;&nbsp;</p><p>(iv)Serious Misconduct under Rule 10.2.13 of BancABC Employment Code of Conduct resulting from Other serious breaches of organizational rules or policy which have the effect of causing an irreparable break down in the employment relationship;</p><p>(v)Serious Misconduct under Rule 10.2.18 of BancABC Employment Code of Conduct resulting from Falsification of records;</p><p>(vi)Serious Breach of Organizational rules and Policy by violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p>', '2021-08-12', '<p>The Committee found the accaused employee guilty of all charges against the accused employee who confessed in all charges except charge number (v).<br></p>', NULL, 'Termination of employment', '<p>Termination of employment<br></p>', '2023-02-21 07:35:44', '2023-02-21 07:35:44'),
(22, 13619, 4, 'N/A', '2021-08-18', '<p>(i)<span style=\"white-space:pre\">	</span>Serious Breach of Organizational rules and Policy by</p><p>&nbsp;violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)<span style=\"white-space:pre\">	</span>Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5, 9, 11.4.1, 13.2.1 (a), 20 (a), (b), (f), (g), 29.16 and 36.2(u) of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”);&nbsp;</p><p>(iii)<span style=\"white-space:pre\">	</span>Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct; and</p><p>(iv)<span style=\"white-space:pre\">	</span>Unacceptable work performance as a Relationship Officer under Section 10.2.4 of the BancABC Employment Code of Conduct.</p>', '2022-09-13', '<p>The Committee found the accused employee guilty in negligence trough failure to be vigilant in verification of some of the KYC documents brought forward by clients.<br></p>', NULL, 'Written warning letter', '<p>&nbsp;Written warning letter<br></p>', '2023-02-21 08:59:00', '2023-02-21 08:59:00'),
(23, 13337, 4, 'N/A', '2021-08-18', '<p>The employee was charged with the following offenses:</p><p>(i)Serious Breach of Organizational rules and Policy by violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5, 9, 11.4.1, 13.2, 20 (a), 29.16 and 36.2(u) of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”);&nbsp;</p><p>(iii)Substantial Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct; and</p><p>(iv)<span style=\"white-space:pre\">	</span>Unacceptable work performance as a Branch Manager under Section 10.2.4 of the BancABC Employment Code of Conduct.</p>', '2021-09-13', '<p>The Committee found the accused employee guilty in five charges agaist her.</p><div><br></div>', NULL, 'Demotion and role change', '<p>&nbsp;Demotion and role change<br></p>', '2023-02-21 09:11:01', '2023-02-21 09:11:01'),
(24, 102186, 1, 'N/A', '2021-10-12', '<p>(i)Substantial Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct;</p><p>(ii)Serious Misconduct under Rule 10.2.18 of BancABC Employment Code of Conduct resulting from Falsification of records or any Company documents;</p><p>(iii)Gross Incompetence or inefficiency in the performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct;</p><p>(iv)Serious Breach of Organizational rules and Policy which have the effect of causing an irreparable break down in the employment relationship by violating Section 7.5, 9, 11.4.1, 13.2.5(c), 13.2.5(f), and 29.16 of Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML Policy”), Section 21(1) and 21(2) of Card Operations Policy and Procedure Manual, under Section 10.2.13 of BancABC Employment Code of Conduct; and Section 5 and 6 of Fraud Management Policy and Procedures.&nbsp;</p>', '2021-10-13', '<p>The accused employee was found guilty in all charges against him.<br></p>', NULL, 'Demotion and role change', '<p>Demotion<br></p>', '2023-02-21 09:13:02', '2023-02-21 09:13:02'),
(25, 101234, 3, 'N/A', '2021-08-18', '<p>(i)Serious Breach of Organizational rules and Policy by violating Section 5 and 6 of Fraud Management Policy and Procedures which provides a duty to all employees of the Bank to guard against fraud and expected to identify process and procedures that may be vulnerable to fraud and to draw such instance to the attention of the Management in your division, under Section 10.2.13 of BancABC Employment Code of Conduct;&nbsp;</p><p>(ii)Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5, 9, 11.4.1, 13.2.1(a), 20(f), (i), and 29.16 of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”);</p><p>(iii)Substantial Negligence in performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct; and (i) Serious Misconduct of breaching organizational rules by violating Section 8.2 and 9 of Credit Policy.&nbsp;</p>', '2021-11-30', '<p>The Committee recommend that the accused employee should be held responsible as Head of Department after it was testified to be a collective action.<br></p>', NULL, 'Written warning letter', '<p>Written Warning Letter<br></p>', '2023-02-21 09:16:09', '2023-02-21 09:16:09'),
(26, 100277, 1, 'N/A', '2022-02-09', '<p>The employee was charged with the following offences;</p><p>(i) Substantial Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct;</p><p>(ii) Gross Incompetence or inefficiency in the performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct;</p><p>(iii) Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5, 9, 11.4.1, 13.2.1(a), 20(f), (i), and 29.16 of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”);</p><p>(iv) Serious Breach of Organizational rules and Policy by violating Section 7.5, 9, 11.4.1, 13.2.5(c), 13.2.5(f), and 29.16 of Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML Policy”), Section 21(1), 21(2), and 21(3) of Card Operations Policy and Procedure Manual, Section 15 of Finance Policy and Procedure Manual, under Section 10.2.13 of BancABC Employment Code of Conduct; and Section 5 and 6 of Fraud Management Policy and Procedures;&nbsp;</p>', '2022-02-25', '<p>a) Committee therefore unanimously found the employee guilty of a reduced Charge 1: i.e. negligence instead of gross negligence.&nbsp;</p><p>b) The Committee have found the employee not guilty of Charges 2, 3 and 4 as stated in the Charge Sheet as they have not been substantiated by the complainant</p>', NULL, 'Written warning letter', '<p>&nbsp;Written warning letter<br></p>', '2023-02-21 09:19:20', '2023-02-21 09:19:20'),
(27, 100937, 4, 'N/A', '2022-04-11', '<p>The employee was charged with the following offences;</p><p>(i) Substantial Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct;</p><p>(ii) Gross Incompetence or inefficiency in the performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct;</p><p>(iii) Failure to be vigilant, monitor, detect and report any suspicious transactions; under Section 6, 7.5, 9, 11.4.1, 13.2.1(a), 20(f), (i), and 29.16 of the Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML/CFT Policy”);</p><p>(iv) Serious Breach of Organizational rules and Policy by violating Section 7.5, 9, 11.4.1, 13.2.5(c), 13.2.5(f), and 29.16 of Anti-Money Laundering and Combating the Financing of Terrorism Policy and Procedure Manual (“AML Policy”), Section 21(1), 21(2), and 21(3) of Card Operations Policy and Procedure Manual, Section 15 of Finance Policy and Procedure Manual, under Section 10.2.13 of BancABC Employment Code of Conduct; and Section 5 and 6 of Fraud Management Policy and Procedures;&nbsp;</p>', '2021-04-27', '<p>a) There was no proper hand over of the duties assigned to Lameck Mushi from the former Manager: Card Operations who was in charge of the reconciliation process.&nbsp;</p><p>b) There were no proper card reconciliation trainings provided to Lameck Mushi on reconciliation.</p><p>c) No proper checkup and effort taken for the manager to understand how the records and information were prepared by his subordinate based on the facts that the subordinate was trusted.</p><p>d) The unit relied heavily on the external group audit report presented in the year 2019 which showed that there were no any misrepresentations or fraud detected in Tanzania, and confirmed that Tanzania had the best reconciliation process compared to other subsidiaries in the group.</p><p>e) Committee also noted that during that time reconciliation was done once a month as despite of a huge number of transactions (over 30,000) to be reconciled and at the same time the accused was supposed to take care of other duties assigned hence he felt over-burdened and not able to work accurately.</p>', NULL, 'Written warning letter', '<p>Written warning letter<br></p>', '2023-02-21 09:21:06', '2023-02-21 09:21:06'),
(28, 100350, 6, 'N/A', '2021-06-24', '<p>The employee was charged with the following offences;</p><p>(i) Substantial Negligence in the performing your duties, under Section 10.2.3 of BancABC Employment Code of Conduct;</p><p>(ii) Gross Incompetence or inefficiency in the performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct;</p>', '2021-07-28', '<p>a) The Committee recognized that the employee has a great&nbsp;</p><p>Sustainable negligence in performing his duties in charge no 1 however, the Committee also notes that this factor; nor his claim to be human error does not exonerate the employee from his core and key responsibility to ensure that he is vigilant, he should have followed the proper change management process.</p><p>b) Concerning the charge 2 Dishonesty or any other breach of trust, failure to not telling the MD the truth on the process that was done to temporary resolve his issue; the Chairperson and her Committee have found that the Accused employee guilty of this charge.&nbsp;</p><p>c) The Committee therefore unanimously found the employee guilty of all the charges.</p>', NULL, 'Written warning letter', '<p>Written warning letter<br></p>', '2023-02-21 09:22:50', '2023-02-21 09:22:50'),
(29, 100350, 6, 'N/A', '2021-08-16', '<p>The employee was charged with the following offence;</p><p>(i) Being under the influence of alcohol whilst at work and consuming alcohol whilst on duty, under Section 10.2.12 of BancABC Employment Code of Conduct;</p>', '2021-09-05', '<p>a) The Committee recognized that the employee’s behavior is not acceptable and cannot be entertained by the bank since he is a senior employee that the juniors are looking up to him for guidance. He should have controlled his alcohol intake including not taking alcohol in the office, during working hours and in front of his subordinates.</p><p>b) The Committee has therefore unanimously found the employee guilty of the charge.</p>', NULL, 'Final warning letter', '<p>&nbsp;Final warning letter<br></p>', '2023-02-21 09:24:44', '2023-02-21 09:24:44'),
(30, 13522, 4, 'Suspended from Duty', '2021-06-28', '<p>The employee was charged with the following offences;</p><p>(i) Falsification of records or any company documents, under Section 10.2.18 of BancABC Employment Code of Conduct;</p><p>(ii) Fraud or misappropriation of Organizational funds under Rule 10.2.10 of BancABC Employment Code of Conduct;</p><p>(iii) Acts of theft, misappropriation or willful dishonesty against the employer under Rule 10.2.9 of BancABC Employment Code of Conduct;</p><p>(iv) Dishonesty or any other breach of trust under Rule 10.2.5 of BancABC Employment Code of Conduct;</p><p>(v) Gross Incompetence or Inefficiency in Performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct;</p><p>(vi) Absence from work without Permission and Doing unauthorized private work or matters during office hours under Rule 10.2.1 and 10.1.6 of BancABC Employment Code of Conduct.</p>', '2021-08-02', '<p>The Committee found the employee guilty of the following charges:</p><p>a) Charge no.1 of falsification of records or any company documents, under Section 10.2.18 of BancABC Employment Code of Conduct by deliberately submitted to the Management forged contracts/lease agreements and rent claims bearing forged names and account information of persons purporting to be the landlords for the Liwale, Newala and Lindi satellite office;</p><p>b) Charge no.4 of dishonesty or any other breach of trust under Rule 10.2.5 of BancABC Employment Code of Conduct. Without Management approval, he deliberately and fraudulently entered into lease agreement with fake landlords purporting to be landlords of Liwale, Newala, Mtwara and Lindi satellite offices;</p><p>c) Charge no.5 (ii) Gross Incompetence or Inefficiency in Performance of work under Rule 10.2.6 of BancABC Employment Code of Conduct.</p>', NULL, 'Termination of employment', '<p>Termination of employment<br></p>', '2023-02-21 09:33:07', '2023-02-21 09:33:07'),
(31, 13389, 1, NULL, '2022-10-24', '<p>The employee was charged with the following offences:</p><p>(i) Act of theft, misappropriation, or willful dishonesty against the employer, under Section 10.2.9 of BancABC Employment Code of Conduct &amp; Grievance Procedure;</p><p>(ii) Dishonesty and breach of trust, under Section 10.2.5 of BancABC Code of Conduct on Disciplinary &amp; Grievance Procedure.</p>', '2022-11-04', '<p>The Committee found the employee guilty of the following charges:</p><p>a) Act of theft, misappropriation, or willful dishonesty against the employer, under Section 10.2.9 of BancABC Employment Code of Conduct &amp; Grievance Procedure;</p><p>b) Dishonesty and breach of trust, under Section 10.2.5 of BancABC Code of Conduct on Disciplinary &amp; Grievance Procedure.</p>', NULL, 'Termination of employment', '<p>Termination of employment<br></p>', '2023-02-21 09:54:29', '2023-02-21 09:54:29'),
(32, 13521, 1, 'N/A', '2022-11-14', '<p>The employee was charged with the following offences:</p><p>(i) Serious misconduct of being absent from work without permission or reasonable cause for over five (5) working days, under Section 10.2 of BancABC Employment Code of Conduct on Disciplinary &amp; Grievance Procedure.</p>', '2022-12-20', '<p>The Committee found the employee guilty of the charge:</p><p>a) Serious misconduct of being absent from work without permission or reasonable cause for over five (5) working days, under Section 10.2.1 of BancABC Employment Code of Conduct on Disciplinary &amp; Grievance Procedure.</p>', NULL, 'Termination of employment', '<p>Termination of employment<br></p>', '2023-02-21 10:20:14', '2023-02-21 10:20:14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `disciplinaries`
--
ALTER TABLE `disciplinaries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `disciplinaries`
--
ALTER TABLE `disciplinaries`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
